repos:
  - repo: local
    hooks:
      - id: stylua
        name: StyLua
        language: rust
        entry: stylua
        types: [lua]
        args: ["-"]
      - id: luacheck
        name: luacheck
        language: system
        entry: luacheck
        types: [lua]
        args: [.]
